config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :poems
  resources :galleries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :stories, :path => 'jobs'
  
  
  resources :people
  resources :pins, :path => 'history'
  devise_for :users
  root 'stories#index'
  devise_scope :user do get 'users/sign_out' => "devise/sessions#destroy"
  end
  
resources :startups, :path => 'directory'
  

  
  get 'home/photos'
  get 'home/index'
  get 'home/about', :path => 'about'
  get 'home/sponsor'
  

  resources :stories
  get "search", to: "search#search"

end

app/models/poem.rb
class Poem < ActiveRecord::Base
    belongs_to :user
    
    validates_formatting_of :header_image, using: :url
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = current_user.poems.build
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = current_user.poems.build(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :content, :header_image, :facebook_url, :twitter_url, :source, :name)
    end
end

def correct_user
  @poem = current_user.poems.find_by(id: params[:id])
  redirect_to poems_path, notice: "Not authorized to edit this poem" if @poem.nil?
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/_form.html.erb
<style>
#wrapper-copyright {
  display: none;
}

#main-container-footer{
  display: none;
}
</style>

<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, placeholder: 'Writers Name', class: "form-control" %><br>
    
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: 'The Journey', class: "form-control" %><br>
    
    <!--mints Gallery-->
    <div id="page-head-text-hide-on-mobile">
    <hr style="border-top: 1px solid #00d49b;">
    <%= link_to home_photos_path, target: "_blank" do %><i style="font-size: 25px;" class="fa fa-camera" title="mints Gallery"></i><% end %>
    <span style="margin-left: 16%;"><strong>Click</strong> to explore images in the mints gallery.</span>
    <br>
    <br>
    <hr style="border-top: 1px solid #00d49b;">
    <br>
    </div>
   <!--end-->
    
    <%= f.label :image %><br>
    <%= f.text_field :header_image, placeholder: 'Recommended  800 x 500 | http://www.google.com/url_to_image.png', class: "form-control" %><br>
    
    <%= f.label :Share_Your_Poem %><br>
    <%= f.text_area :content, placeholder: '|... ', class: "form-control" %><br>

    <%= f.label :twitter %><br>
    <%= f.text_field :twitter_url, required: false, placeholder: 'http://www.lavail.io/profile-name | Optional', class: "form-control" %><br>
    
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook_url, placeholder: 'http://www.facebook.com/profile-name | Optional', class: "form-control" %><br>
    
        <%= f.label :source %><br>
    <%= f.text_field :source, placeholder: 'http://www.facebook.com/profile-name | Optional', class: "form-control" %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>


<!DOCTYPE HTML>
<html>

<head>
<style>
#wrapper-navbar{
    margin-top: -10px;
}

.img-fluid {
	width: 440px;
	height: 330px;
}
</style>


</head>

<body>

<a name="ancre"></a>

<!-- CACHE -->
<div class="cache"></div>


<!-- NAVBAR -->

<!--moved to partial-->

<!-- FILTER -->	

	<div id="main-container-menu" class="object">
    	<div class="container-menu">
        	
            <div id="main-cross">
            	<div id="cross-menu"></div>
            </div>
            
            <div id="main-small-logo">
            	<div class="small-logo"></div>
            </div>
            
            <div id="main-premium-ressource">
                <div class="premium-ressource"><a href="#">Premium resources</a></div>
            </div>
            
            <div id="main-themes">
                <div class="themes"><a href="#">Latest themes</a></div>
            </div>
            
            <div id="main-psd">
                <div class="psd"><a href="#">PSD goodies</a></div>
            </div>
                
            <div id="main-ai">
                <div class="ai"><a href="#">Illustrator freebies</a></div>
            </div>
            
            <div id="main-font">
                <div class="font"><a href="#">Free fonts</a></div>
            </div>
            
            <div id="main-photo">
                <div class="photo"><a href="#">Free stock photos</a></div>
            </div>
            
        </div>
    </div>


<!-- PORTFOLIO -->

	<div id="wrapper-container">
    
		<div class="container object">

			<div id="main-container-image">
                       <h4 class="page-head-text" id="page-head-text-hide-on-mobile">Need some inspiration? <br> Search the mints photo gallery. <%= link_to 'mints', home_photos_path, target: "_blank" %> </h4>
					<section class="work">
						<!--permanent card -->
						<figure class="white">
							<a href="#">
								<%= image_tag "/assets/mint-poem" %>
								<dl>
									<!--<dt></dt>-->
									<dd><em><strong>‘Give me a place to stand and I shall move the earth.’</strong></em>. <br><br>Share your poetry with the rest of the world. Start your collection, or upload the poetry you've already written.</dd>	
								</dl>
							</a>
              <div id="wrapper-part-info">
            	<div class="part-info-image"><%= link_to new_poem_path do %><i style="font-size: 30px;" class="fa fa-plus-circle" title="Submit a poem"></i><% end %></div>
              <div id="part-info"> </div>
							</div>
							<!--permanent card end-->
						</figure>
						
			<!--promoted card-->
			<figure class="white" id="page-head-text-hide-on-mobile">
			<a href="#">
				<%= image_tag "/assets/mint-photos" %>
				<dl>
				<dt><%= link_to 'mints', home_photos_path, target: "_blank" %></dt>
				<br>
				<dd>Looking for a high resolution photo for your next Poem? Well we've got you covered. Search the Mints Gallery for the right shot.</dd>	
				</dl>
			</a>
			  <div id="wrapper-part-info">
				<div class="part-info-image"><%= link_to home_photos_path, target: "blank" do %><i style="font-size: 23px;" class="fa fa-camera" title="Find a photo in our Gallery"></i><% end %></div>
			  <div id="part-info"> </div>
			
			<!--promoted card end--></figure>	
						
						<% @poems.each do |poem| %>
						<figure class="white">
							<a href="#" style="text-decoration: none;pointer-events: none; cursor: default;">
								<%= image_tag(poem.header_image, class: 'img-fluid') %>
								<dl>
									<dt>by <%= link_to poem.name, poem %></dt><br>
									<dd><%= truncate(poem.content, length: 100) { link_to "Continue", poem } %></dd>	
								</dl>
							</a>
              <div id="wrapper-part-info">
              <!--<div class="part-info-image"><img src="assets/icon-psd.svg" alt="" width="28" height="28"/></div>-->
              <div id="part-info"><%= poem.title %></div>
							</div>
             </figure>	
						<% end %>
                        
					</section>
                    
				</div>	
            	    
			</div>
         
    <div id="wrapper-oldnew">
    	<div class="oldnew">
        	<div class="wrapper-oldnew-prev">
            	<div id="oldnew-prev"></div>
        	</div>
            <div class="wrapper-oldnew-next">
            	<div id="oldnew-next"></div>
    		</div>
        </div>
	</div>     
            
	<div id="wrapper-thank">
    	<div class="thank">
        	<div class="thank-text">P<span style="letter-spacing:-5px;">o</span>ems</div>
    	</div>
	</div>

</div>



<!-- SCRIPT -->

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!--<script type="text/javascript" src="js/jquery.scrollTo.min.js"></script>-->
    <!--<script type="text/javascript" src="js/jquery.localScroll.min.js"></script>-->
	<!--<script type="text/javascript" src="js/fastclick.min.js"></script>-->
	<!--<script type="text/javascript" src="js/jquery.animate-colors-min.js"></script>-->

	
<script>
	

</script>


</body>


</html>

app/views/poems/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<head>
 <meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<!--google font-->
<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

<style>
.work {

    background-size: cover;
}

#wrapper-navbar{
    margin-top: -10px;
}

  #wrapper-copyright{
    display:none;
  }
  
.img-post {
    width: 100%;
}
  
.title-text{
	font-family: Helvetica, sans-serif;
	-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 22px;
	font-weight:600;
	color:#686868;
	line-height:125%;
	height:auto;
	width:calc(100% - 88px);
	margin-top:8px;
}

.title-text-2{
	font-family: Helvetica, sans-serif;
	-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 15px;
	font-weight:400;
	color:#A1A1A1;
	line-height:125%;
	height:auto;
	width:calc(100% - 88px);
	margin-top:8px;
	display: hidden;
}

.post-content {
    margin-top: 3%;
}

#post-content {
    line-height: 37px;
    font-size: 20px;
    letter-spacing: 1px;
    font-family: 'Playfair Display', serif;
    text-align: center;
}

.work{
    padding-top: 6%;
}

.img-caption {
    margin-top: -20%;
}


</style>
</head>

 <%= image_tag @poem.header_image, class: "img-post" %>
 <div class="gallery-text">
     <%= @poem.title %>
 </div>
 <!--dont remove-->
 <div class="img-caption" style="font-size: 20px;"></div>
 <!--dont remove end-->
 
<div id="wrapper-container">
    
		<div class="container object">

			<div id="main-container-image">
                <div class="title-item">
                	<div class="title-icon"></div>
                    <div class="title-text"><%= @poem.title %></div>
                    <div class="title-text-2">By: <%= @poem.name %>
                    <%= @poem.created_at.strftime("%b %d, %Y") %></div>
                    <br>
                    <!--User controls-->
                    <% if user_signed_in? %>
                    <%= link_to edit_poem_path(@poem) do %><i style="font-size: 15px;" class="fa fa-pencil"></i><% end %> &nbsp &nbsp| &nbsp
                    <%= link_to 'Back', poems_path %>
                    <% end %>
                </div>
				<div class="work">
				 
					<figure class="white">
							 <!--<img src="img/psd-4.jpg" alt="" />-->
        <!--                 <div id="wrapper-part-info">-->
        <!--                     <div class="part-info-image-single">-->
                               <!--share on twitter-->
        <!--                       <i class="fa fa-twitter" aria-hidden="true"></i>-->
                                
        <!--                     </div>-->
						  <!--</div>-->
                    </figure>	
</div>
<!--content start-->
<div class="post-content">
    <dl>
	    <dt style="font-size: 40px; color: rgb(104, 104, 104); text-align:center;"></dt>
			<p><%= simple_format(@poem.content, id: "post-content") %></p>
			<br>
			<!--source url-->
			<%= link_to @poem.source, target: "_blank" do %><i style="font-size: 20px;" class="fa fa-wikipedia-w" title="Source"></i><% end %>
			<br>
			<br>
			<% if @poem.twitter_url.blank? && @poem.facebook_url.blank? %>
                <p>No Twitter Added</p><br>
                <p>No Facebook Added</p>
            <% elsif @poem.facebook_url.blank? %>
                <p>No Facebook Added</p><br>
            <%= link_to @poem.twitter_url, target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-twitter" title="Writer's Twitter"></i><% end %>
            <% elsif @poem.twitter_url.blank? %>
                <p>No Twitter Added</p><br>
            <%= link_to @poem.facebook_url, target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-facebook" title="Writer's Facebook"></i><% end %>
            <% else %>
            <%= link_to @poem.facebook_url, target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-facebook" title="Writer's Facebook"></i><% end %>
                <br>
                <br>
			<%= link_to @poem.twitter_url, target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-twitter" title="Writer's Twitter"></i><% end %>
			<% end %>
  			 </dl>
  			  <div class="social-content">
  			    <div class="facebook object">
				<%= link_to "http://twitter.com/home?status=This poem titled #{@poem.title} is a must read! Read it here. #{story_url(@poem)}. And share your poetry on minttoday.com", target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-twitter" title="Share on Twitter"></i><% end %>
	        </div>
  	      </div>
      </div>
    </div>
        </div>
      </div>  