config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :poems
  resources :galleries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :stories, :path => 'jobs'
  
  
  resources :people
  resources :pins, :path => 'history'
  devise_for :users
  root 'stories#index'
  devise_scope :user do get 'users/sign_out' => "devise/sessions#destroy"
  end
  
resources :startups, :path => 'directory'
  

  
  get 'home/photos'
  get 'home/index'
  get 'home/about', :path => 'about'
  get 'home/sponsor'
  

  resources :stories
  get "search", to: "search#search"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    
    validates_formatting_of :image_url, using: :url
    validates_formatting_of :wiki_url, using: :url
    
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
    @pins = Pin.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image_url, :title, :wiki_url)
    end
end

def correct_user
  @pin = current_user.pins.find_by(id: params[:id])
  redirect_to pins_path, notice: "Not authorized to edit this post" if @pin.nil?
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :title, placeholder: 'Martin Luther King Jr', class: "form-control" %><br>
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: '...| ', class: "form-control" %><br>
    <%= f.label :image %><br>
    <!--add file size validation-->
    <%= f.text_field :image_url, placeholder: 'Recommended  800 x 500 | http://www.lavail.io/url_to_company_logo.png', class: "form-control" %><br>
    <%= f.label :source %><br>
    <%= f.text_field :wiki_url, placeholder: 'http://wikipedia.org', class: "form-control" %><br>

  </div>
  <div class="actions">
    <%= f.submit "Submit",class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<style>
#wrapper-copyright {
  display: none;
}

#main-container-footer{
  display: none;
}

#wrapper-navbar {
  margin-top: -20px;
}
.head-text {
    
}
</style>

    
<%= render 'form' %>
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', @pin %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<style>
#wrapper-copyright{
    
}
</style>
<div class="panel panel-default">
    <div class="panel-heading">
    </div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

app/views/pins/show.html.erb
<head>
 <meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<!--google font-->
<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

<style>
.work {

    background-size: cover;
}

#wrapper-navbar{
    margin-top: -10px;
}

  #wrapper-copyright{
    display:none;
  }
  
.img-post {
    width: 100%;
}
  
.title-text{
	font-family: Helvetica, sans-serif;
	-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 22px;
	font-weight:600;
	color:#686868;
	line-height:125%;
	height:auto;
	width:calc(100% - 88px);
	margin-top:8px;
}

.title-text-2{
	font-family: Helvetica, sans-serif;
	-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 15px;
	font-weight:400;
	color:#A1A1A1;
	line-height:125%;
	height:auto;
	width:calc(100% - 88px);
	margin-top:8px;
	display: hidden;
}

.post-content {
    margin-top: 12%;
}

#post-content {
    line-height: 42px;
    font-size: 20px;
    letter-spacing: 1px;
    font-family: 'Playfair Display', serif;
}

.work{
    padding-top: 6%;
}

.img-caption {
    margin-top: -20%;
}
</style>
</head>

 <%= image_tag @pin.image_url, class: "img-post" %>
 <div class="gallery-text">
     <%= @pin.title %>
 </div>
 <!--dont remove-->
 <div class="img-caption" style="font-size: 20px;"></div>
 <!--dont remove end-->
 
<div id="wrapper-container">
    
		<div class="container object">

			<div id="main-container-image">
                <div class="title-item">
                	<div class="title-icon"></div>
                    <div class="title-text"><%= @pin.title %></div>
                    <div class="title-text-2">Published: <%= @pin.created_at.strftime("%b %d, %Y") %></div>
                    <br>
                    <!--User controls-->
                    <% if user_signed_in? %>
                    <%= link_to edit_pin_path(@pin) do %><i style="font-size: 15px;" class="fa fa-pencil"></i><% end %> &nbsp &nbsp| &nbsp
                    <%= link_to 'Back', home_index_path %>
                    <% end %>
                </div>
				<div class="work">
				 
					<figure class="white">
							 <!--<img src="img/psd-4.jpg" alt="" />-->
        <!--                 <div id="wrapper-part-info">-->
        <!--                     <div class="part-info-image-single">-->
                               <!--share on twitter-->
        <!--                       <i class="fa fa-twitter" aria-hidden="true"></i>-->
                                
        <!--                     </div>-->
						  <!--</div>-->
                    </figure>	
                    </div>
                    <!--content start-->
					<div class="post-content">
					    <dl>
            			    <dt style="font-size: 40px; padding-bottom: 60px; color: rgb(104, 104, 104); text-align:center;"><%= @pin.title %></dt>
            					<p><%= simple_format(@pin.description, id: "post-content") %></p>
            					<br>
            					<!--source url-->
            					
            					<%= link_to @pin.wiki_url, target: "_blank" do %><i style="font-size: 15px;" class="fa fa-wikipedia-w" title="Supported Source"></i><% end %><br>
          						 </dl>
          						  <div class="social-content">
          						    <div class="facebook object">
                    				<%= link_to "http://twitter.com/home?status=Intro to History 101. An individual named #{@pin.title} #{pin_url(@pin)}", target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-twitter" title="Share on Twitter"></i><% end %>
                    			</div>
          						  </div>
						          </div>
                  </div>
                </div>
              </div>  