config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :poems
  resources :galleries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :stories, :path => 'jobs'
  
  
  resources :people
  resources :pins, :path => 'history'
  devise_for :users
  root 'stories#index'
  devise_scope :user do get 'users/sign_out' => "devise/sessions#destroy"
  end
  
resources :startups, :path => 'directory'
  

  
  get 'home/photos'
  get 'home/index'
  get 'home/about', :path => 'about'
  get 'home/sponsor'
  

  resources :stories
  get "search", to: "search#search"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :js
  
  def index
    @pins = Pin.all
    @pins = Pin.paginate(:page => params[:page], :per_page => 9)
  end
  
  def photos
  
  end
  
  def about
  end
  
  def sponsor
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.1.erb
<style>

</style>
<!--wrapper content bottom   -->
	<div id="main-container-footer">
		<div class="container-footer">
        	
            <div id="row-1f">
            	<div class="text-row-1f"><span style="font-weight:600;font-size:15px;color:#666;line-height:250%;text-transform:uppercase;letter-spacing:1.5px;">What is mints</span><br><em>(Minorities In Todays Society)</em> is a lightweight platform showcasing the history, efforts, and talents of the underrepresented communities.</div>
            </div>
            
            <div id="row-2f">
            	<div class="text-row-2f"><span style="font-weight:600;font-size:15px;color:#666;line-height:250%;text-transform:uppercase;letter-spacing:1.5px;">How does it work</span><br>mints runs from user generated content. The idea is to share experiences, history and knowledge within the underrepresented community. Let's try something new! </div>
            </div>
            
            <div id="row-3f">
            	<div class="text-row-3f"><span style="font-weight:600;font-size:15px;color:#666;line-height:250%;text-transform:uppercase;letter-spacing:1.5px;">Get in touch!</span><br>Have a question? Or maybe you'd like to say hi. follow us on Facebook & Twitter to keep updated.
            	    <br>
            	    <br>
            	    <a href="https://twitter.com/mint_today" target="blank"><i style="font-size: 20px;" class="fa fa-twitter" title="Give us a follow"></i></a>&nbsp&nbsp
            	    <a href="https://www.facebook.com/minttoday/" target="blank"><i style="font-size: 20px;" class="fa fa-facebook" title="Give us a page like"></i></a>
            	</div>
            </div>
            
              <div id="row-4f">
            	<div class="text-row-4f"><span style="font-weight:600;font-size:15px;color:#666;line-height:250%;text-transform:uppercase;letter-spacing:1.5px;">Opensource</span><br>Do you love coding and contributing to projects? or Need some hands on practice?. Follow the project developer <a href="https://www.twitter.com/arisnance" target="blank"><i style="font-size: 20px;" class="fa fa-twitter" title="Click to be taken to Twitter"></i></a>&nbsp and send a direct message.
            	    <br>
            	    <br><em>Happy Coding</em>.
                </div>

				<!--<div id="main_tip_newsletter"> -->
				<!--	<form>-->
				<!--		<input type="text" name="newsletter" id="tip_newsletter_input" list="newsletter" autocomplete=off required>-->
				<!--	</form>-->
				<!--</div>-->
            </div>
            
		</div>
	</div>
<!--end-->
   
    <div id="wrapper-copyright">
		<div class="copyright">
    		<div class="copy-text object">Mints © 2017. Developed by <a style="color:#D0D1D4;" href="http://lavail.io/" target="blank">@ArisNance</a></div>
    		
			<!--<div class="wrapper-navbouton">-->
   <!-- 			<div class="facebook object">-->
   <!-- 				<a href="#" target="blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>-->
   <!-- 			</div>-->
   <!-- 			<div class="facebook object">-->
   <!-- 				<a href="#" target="blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>-->
   <!-- 			</div>-->
   <!-- 		</div>-->
    	</div>
    </div>

app/views/home/_footer.html.erb
<footer class="footer">
                <nav class="pull-left">
                    <ul>

                        <li>
                           <%= link_to 'Jobs', stories_path %>
                        </li>
                        <li>
                           <%= link_to 'Events', events_path %>
                        </li>
                        <li>
                           <%= link_to 'Directory', startups_path %>
                        </li>
                        <li>
                           <%= link_to 'About', home_about_path %>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                  Minttoday  © 2017, made with <i class="fa fa-heart heart"></i> by <a href="http://www.lavail.io" target="blank">Aris Nance</a>
                </div>
        </footer>

app/views/home/_header.html.erb
<!--<nav class="navbar navbar-default">-->
<!--  <div class="container">-->
    <!-- Brand and toggle get grouped for better mobile display -->
<!--    <div class="navbar-header">-->
<!--      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">-->
<!--        <span class="sr-only">Toggle navigation</span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
<!--      </button>-->
<!--      <%= link_to "Pinterested", root_path, class: "navbar-brand" %>-->
<!--    </div>-->

    <!-- Collect the nav links, forms, and other content for toggling -->
<!--    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
<!--      <ul class="nav navbar-nav">-->
        
<!--      </ul>-->
      
<!--      <ul class="nav navbar-nav navbar-right">-->
        
<!--        <li><%= link_to "Home", root_path %></li>-->
<!--        <li><%= link_to 'About Me', home_photos_path %></li>-->
        
        <!--<% if user_signed_in? %>-->
        <!--  <li><%= link_to "List Pins", pins_path %></li>-->
        <!--  <li><%= link_to "New Pins", new_pin_path %></li>-->
        <!--  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>-->
        <!--  <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>-->
        
        <!--<% else %>-->
        <!--  <li><%= link_to "Login", new_user_session_path %></li>-->
        <!--  <li><%= link_to "Join", new_user_registration_path %></li>-->
        
        <!--<% end %>-->
        
<!--      </ul>-->
<!--    </div><!-- /.navbar-collapse -->
<!--  </div><!-- /.container-fluid -->
<!--</nav>-->

app/views/home/_navi.html.1.erb
<div id="wrapper-navbar">
		<div class="navbar object">
    		<div id="wrapper-sorting">
            <div id="wrapper-title-1">
            <!--<div class="top-rated object">BLacK History</div>-->
            <%= link_to image_tag("mints-logo.png"), root_path, id: "logo" %>
            	<div id="fleche-nav-1"></div>
    		</div>
            
      <!--      <div id="wrapper-title-2">-->
            <!--<a href="#"><div class="recent object">Leaders Today</div></a>-->
      <!--      <%= link_to 'mints', people_path, class: "top-rated object", title: "See who's open to networking." %>-->
      <!--          <div id="fleche-nav-2"></div>-->
    		<!--</div>-->
            
            <div id="wrapper-title-3">
            <!--<a href="#"><div class="oldies object">StartUps</div></a>-->
            <%= link_to 'Directory', startups_path, class: "oldies object", title: "Community directory. Post now." %>
                <div id="fleche-nav-3"></div>
    		</div>
    		
    		 <div id="wrapper-title-3">
            <!--<a href="#"><div class="oldies object">Stories</div></a>-->
            <%= link_to 'jobs', stories_path, class: "oldies object", title: "Post or Find jobs  " %>
                <div id="fleche-nav-3"></div>
    		</div>
    		
    		<div id="wrapper-title-3">
            <a href="#" style="pointer-events: none;"><div class="oldies object">Give</div></a>
            <%= link_to '', class: "oldies object", title: "Read, Write, & Share Poety." %>
            <div id="fleche-nav-3"></div>
    		</div>
    		<div id="wrapper-title-3">
            <!--<a href="#"><div class="oldies object">Stories</div></a>-->
            <%= link_to 'Events', events_path, class: "oldies object events", title: "Find evenets nearby. Post now for free!" , style: "pointer-events: ; color: #424242;" %>
            <div id="fleche-nav-3"></div>
    		</div>
    		
            </div>
            <div id="wrapper-bouton-icon">
                <% if user_signed_in? %>
            	<div id="bouton-ai"><%= link_to "Logout", destroy_user_session_path, method: :delete, style: 'font-size: 11px;' %></div>
            	<%= link_to edit_user_registration_path, id: "bouton-psd" do %><i style="font-size: 15px;" class="fa fa-pencil" title="Edit Account"></i><% end %>
            	<% else %>
            	<div id="bouton-theme"><%= link_to "Login", new_user_session_path %></div>
            	<div id="bouton-font"><%= link_to "Join", new_user_registration_path %></div>
            	<!--<div id="bouton-photo"><img src="assets/icon-photo.svg" alt="photo" title="Photo" height="28" width="28"></div>-->
            	<!--<div id="bouton-premium"><img src="assets/icon-premium.svg" alt="premium" title="Premium" height="28" width="28"></div>-->
            	<% end %>
			</div>
    	</div>
    </div>
<!-- HEADER -->

<div id="wrapper-header">
	<div id="main-header" class="object">
		<!--<div class="logo">-->
		<!--<%= link_to image_tag("mints-logo.png"), root_path %>-->
		<!--</div>-->
		
        <div id="main_tip_search"> 
			<form>
				<input type="text" name="search" id="tip_search_input" list="search" autocomplete=off required>
			</form>
		</div>
        <div id="stripes"></div>
    </div>
</div>

app/views/home/_navi.html.erb
<nav class="navbar navbar-default">
    <div class="logo">
        <a href="#" class="simple-text">
            <%= link_to image_tag('mints-logo.png'), root_path %>
        </a>
    </div>
        <div class="container-fluid">
            <div class="navbar-header">
                <div class="dropdown" id="mobile-dropdown">
              <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
                  Menu
                  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <!--<li><a href="#paper">About Mints</a></li>-->
                <!--<li><a href="#paper">Another action</a></li>-->
                <!--<li><a href="#paper">Something else here</a></li>-->
                <li class="divider"></li>
                <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <li><%= link_to 'Add an Event', new_event_path %></li>
                <li><%= link_to 'Post a Job', new_story_path %></li>
                <li><%= link_to 'Directory Submission', new_startup_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Local Events', events_path %></li>
                <li><%= link_to 'Explore Careers', stories_path %></li>
                <li><%= link_to 'Free Directory', startups_path %></li>
                <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to 'Local Events', events_path %></li>
                <li><%= link_to 'Explore Careers', stories_path %></li>
                <li><%= link_to 'Free Directory', startups_path %></li>
                <% end %>
              </ul>
        </div>
                <a class="navbar-brand" href="#"></a>
            </div>
            <div class="collapse navbar-collapse">

                <form class="navbar-form navbar-left navbar-search-form" role="search">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        <input type="text" value="" class="form-control" placeholder="Search...">
                    </div>
                </form>

                <div class="dropdown">
              <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
                  Menu
                  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <!--<li><a href="#paper">About Mints</a></li>-->
                <!--<li><a href="#paper">Another action</a></li>-->
                <!--<li><a href="#paper">Something else here</a></li>-->
                <li class="divider"></li>
                <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <li><%= link_to 'Add an Event', new_event_path %></li>
                <li><%= link_to 'Post a Job', new_story_path %></li>
                <li><%= link_to 'Directory Submission', new_startup_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Local Events', events_path %></li>
                <li><%= link_to 'Explore Careers', stories_path %></li>
                <li><%= link_to 'Free Directory', startups_path %></li>
                <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
              </ul>
        </div>
            </div>
        </div>
    </nav>

app/views/home/_photos.html.erb
Yay it worked!

app/views/home/_sidebar.html.erb
    <div class="sidebar" data-background-color="white" data-active-color="danger">

    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->

    	<div class="sidebar-wrapper">
    	    <!--<%= Date.today.strftime('%a, %b %d %Y') %>-->
            <!--<div class="logo">-->
            <!--    <a href="#" class="simple-text">-->
            <!--        <%= link_to image_tag('mints-logo.png'), root_path %>-->
            <!--    </a>-->
            <!--</div>-->

            <ul class="nav">

                <!--community page-->
                <li class="active">
                  <a href="dashboard.html">
                        <i class="ti-panel"></i>
                    <p><%= link_to 'Local Events', events_path %></p>
                  </a>
                </li>
                
                <!--inbox page-->
                <li class="active">
                  <a href="#">
                        <i class="ti-panel"></i>
                    <p><%= link_to 'Explore Careers', stories_path %></p>
                  </a>
                </li>
                <!--user profile page-->
                <li class="active">
                  <a href="#">
                        <i class="ti-panel"></i>
                    <p><%= link_to 'Free Directory', startups_path %></p>
                  </a>
                </li>
                           
                <li class="active">
                  <a href="#">
                        <i class="ti-panel"></i>
                    <% if user_signed_in? %>
                    <p><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
                    <% else %>
                    <p><%= link_to "Login", new_user_session_path %></p>
                    <% end %>
                  </a>
                </li>

				<li class="active-pro">
                    <a href="#">
                        <i class="ti-export"></i>
                        
                        <p>Become a Sponsor</p>
                    </a>
                </li>

                
            </ul>
            
    	</div>
    </div>

app/views/home/about.html.erb
<style>
.container-fluid {
    width: 88%;
}

.main-panel{
width:100%;
margin-top: -1%;
}

.sidebar {
    display:none;
}

.card {
    box-shadow:none;
}

.title{
color:#364c56;
}

.category{
font-weight: 600;
font-size: 10px;
text-transform: uppercase;
}

.featurette {
margin-top: 10%;
}

.featurette-image{
width: 20%;
}

.featurette-heading{
margin-top: 10%;
}

.img-circle {
border-radius: 30%;
}
</style>
<body>
<%= render 'home/sidebar' %>
<div class="wrapper">


    <div class="main-panel">

<!--header-->

<div class="content">
  <div class="container-fluid">
      <div class="row">
<!--card-->
<div class="col-md-12">
<h4 class="title">So, What is Minttoday all About?</h4>
<!--<p class="category">Learn more about becoming a <%= link_to 'Sponsor', home_sponsor_path %> </p>-->
<div class="card">
<div class="header">

</div>
<!--<div class="content">-->


<!--<p></p>-->

<!--</div>-->

</div>
 <!-- First Featurette -->
        <div class="featurette" id="about">
            <img class="featurette-image img-circle img-responsive pull-right" src="http://www.creativelysimpledesign.com/wp-content/uploads/2017/03/hm-rocket.png">
            <h2 class="featurette-heading">Who are
                <span class="text-muted">We</span>
            </h2>
            <br>
            <p class="lead">Minttoday was initially developed to serve the underrepresented community. Allowing those who wish to share poetry, stories, and create personal profiles to do so with ease. While the idea behind Minttoday was great, it didn't fill a need within the community. Minttoday is now devoted to serving nonprofits, churches, groups and other grassroot organizations. Our goal is to create the worlds <strong>Smartest, Techiest </strong>, & truely free community driven platform.</p>
        </div>


        <!-- Second Featurette -->
        <div class="featurette" id="services">
            <img class="featurette-image img-circle img-responsive pull-left" src="http://www.creativelysimpledesign.com/wp-content/uploads/2017/03/hm-rocket-blast.png">
            <h2 class="featurette-heading">Why we
                <span class="text-muted">Are</span>
            </h2>
            <br>
            <p class="lead"><strong>We Are. Simply because you Are!</strong><br> With so many economical challenges arising. Most nonprofits, community organized groups, & new businesses struggles with remaining relevant. Most websites today charge fees to post, or the website is completely outdated, and the information is completely irrelevant. With Minttoday, anyone, or any entity can post Jobs, Events or add to our Directory <strong>totally free.</strong></p> Like foreverly free!
        </div>


        <!-- Third Featurette -->
        <div class="featurette" id="contact">
            <img class="featurette-image img-circle img-responsive pull-right" src="http://www.creativelysimpledesign.com/wp-content/uploads/2017/03/hm-rocket-space.png">
            <h2 class="featurette-heading">Increased
                <span class="text-muted">Visibility.</span>
            </h2>
            <br>
            <p class="lead">If your organization or business needs an efficient way to communicate with the community, Minttoday is the only sure way to do so. We allow you to post <strong>unlimited</strong> jobs & <strong>unlimited events,</strong> & we even promote your content on social media. <strong>The Point Is. </strong> If your budget is $100.00+, or $0.00 Minttoday is here for you.</p>
        </div>
</div>
<!--end-->
   
       
</div>
</div>
</div>




</div>
</div>


</body>

</html>

app/views/home/index.html.erb
<html>

<head>
 
<style>
	.img-fluid {
	width: 440px;
	height: 330px;
}
</style>
 

  


</head>

<body>

<a name="ancre"></a>

<!-- CACHE -->
<div class="cache"></div>

<!-- HEADER -->


<!-- NAVBAR -->

 
<!--moved to partial-->
 

  

<!-- FILTER -->	

	<div id="main-container-menu" class="object">
    	<div class="container-menu">
        	
            <div id="main-cross">
            	<div id="cross-menu"></div>
            </div>
            
            <div id="main-small-logo">
            	<div class="small-logo"></div>
            </div>
            
            <div id="main-premium-ressource">
                <div class="premium-ressource"><a href="#">Premium resources</a></div>
            </div>
            
            <div id="main-themes">
                <div class="themes"><a href="#">Latest themes</a></div>
            </div>
            
            <div id="main-psd">
                <div class="psd"><a href="#">PSD goodies</a></div>
            </div>
                
            <div id="main-ai">
                <div class="ai"><a href="#">Illustrator freebies</a></div>
            </div>
            
            <div id="main-font">
                <div class="font"><a href="#">Free fonts</a></div>
            </div>
            
            <div id="main-photo">
                <div class="photo"><a href="#">Free stock photos</a></div>
            </div>
            
        </div>
    </div>


<!-- PORTFOLIO -->

	<div id="wrapper-container">
    
		<div class="container object">

			<div id="main-container-image">
                       
					<section class="work">
 
						<!--permanent card -->
						<figure class="white">
							<a href="#">
								<%= image_tag "/assets/mint-history" %>
								<dl>
									<!--<dt></dt>-->
									<dd>Because <strong>Black Heritage</strong> should not be resurrected, remembered, and celebrated once a year. This section is dedicated to showcasing prominent Black leaders throughtout history, past and present. You can give back by contributing.</dd>	
								</dl>
							</a>
                            <div id="wrapper-part-info">
                            	<div class="part-info-image"><%= link_to new_pin_path do %><i style="font-size: 30px;" class="fa fa-plus-circle" title="Add to History"></i><% end %></div>
                            	<div id="part-info"> </div>
							</div>
							<!--permanent card end-->
						</figure>	
						<% @pins.each do |pin| %>
						<figure class="white">
							<a href="#" style="text-decoration: none;pointer-events: none; cursor: default;">
								<%= image_tag(pin.image_url, class: 'img-fluid') %>
								<dl>
									<dt><%= link_to pin.title, pin %></dt>
									<br>
									<dd><%= truncate(pin.description, length: 200) { link_to "Continue", pin } %></dd>	
								</dl>
							</a>
                            <div id="wrapper-part-info">
                            	<!--<div class="part-info-image"><img src="assets/icon-psd.svg" alt="" width="28" height="28"/></div>-->
                            	<div id="part-info"><%= pin.title %></div>
							</div>
                        </figure>	
						<% end %>
					</section>

				</div>	
            	    <%= will_paginate @pins %>
			</div>
         
    <div id="wrapper-oldnew">
    	<div class="oldnew">
        	<div class="wrapper-oldnew-prev">
            	<div id="oldnew-prev"></div>
        	</div>
            <div class="wrapper-oldnew-next">
            	<div id="oldnew-next"></div>
    		</div>
        </div>
	</div>     
 
    	</div>
    		<div id="wrapper-thank">
    	<div class="thank">
        	<div class="thank-text">Le<span style="letter-spacing:-5px;">a</span>rn</div>
    	</div>
	</div>
	</div>


  
</div>



<!-- SCRIPT -->

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!--<script type="text/javascript" src="js/jquery.scrollTo.min.js"></script>-->
    <!--<script type="text/javascript" src="js/jquery.localScroll.min.js"></script>-->
	<!--<script type="text/javascript" src="js/fastclick.min.js"></script>-->
 
	<!--<script type="text/javascript" src="js/jquery.animate-colors-min.js"></script>-->

	
<script>
	

 
	<script type="text/javascript" src="js/jquery.animate-colors-min.js"></script>

	
	<script>
	




/* PRELOADER */

// function preloader() {
// 	if (document.images) {
// 		var img1 = new Image();
// 		var img2 = new Image();
// 		var img3 = new Image();
// 		var img4 = new Image();
// 		var img5 = new Image();
// 		var img6 = new Image();
// 		var img7 = new Image();
// 		var img8 = new Image();
// 		var img9 = new Image();
// 		var img10 = new Image();
// 		var img11 = new Image();
// 		var img12 = new Image();
// 		var img13 = new Image();
// 		var img14 = new Image();
// 		var img15 = new Image();
// 		var img16 = new Image();
// 		var img17 = new Image();
// 		var img18 = new Image();
// 		var img19 = new Image();
// 		var img20 = new Image();

// 		img1.src = "assets/psd-4.jpg";
// 		img2.src = "assets/font-1.jpg";
// 		img3.src = "assets/psd-1.jpg";
// 		img4.src = "assets/psd-2.jpg";
// 		img5.src = "assets/ai-1.jpg";
// 		img6.src = "assets/theme-2.jpg";
// 		img7.src = "assets/psd-3.jpg";
// 		img8.src = "assets/font-2.jpg";
// 		img9.src = "assets/font-3.jpg";
// 		img10.src = "assets/ai-2.jpg";
// 		img11.src = "assets/icons-1.jpg";
// 		img12.src = "assets/ui-1.jpg";
// 		img13.src = "assets/font-5.jpg";
// 		img14.src = "assets/theme-2.jpg";
// 		img15.src = "assets/psd-5.jpg";
// 		img16.src = "assets/icons-3.jpg";
// 		img17.src = "assets/font-4.jpg";
// 		img18.src = "assets/theme-3.jpg";
// 		img19.src = "assets/font-6.jpg";
// 		// img20.src = "assets/theme-4.jpg";
// 	}
// }
// function addLoadEvent(func) {
// 	var oldonload = window.onload;
// 	if (typeof window.onload != 'function') {
// 		window.onload = func;
// 	} else {
// 		window.onload = function() {
// 			if (oldonload) {
// 				oldonload();
// 			}
// 			func();
// 		}
// 	}
// }
// addLoadEvent(preloader);

  
</script>


</body>


</html>

app/views/home/photos.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <!-- Behavioral Meta Data -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="http://juanvargas.net/Unsplash/css/style.css">
    
<style>
@media only screen and (min-device-width : 375px) and (max-device-width : 667px) { 
.container {
	width: auto !important;
	}
}
</style>
  </head>
    <body>

      <div class="message_holder">
        <div class="message">
          <span style="margin-left: 35%;">All high-resolution photos are provided courtesy of <strong><a href="https://unsplash.com/" target="blank">Unsplash</a></strong>.</span>
          <br>
          <span style="margin-left: 35%;"><strong>Right-Click</strong> to copy the image address or Click to visit Unsplash.</span>
          <!--<div id = "div_id">-->
          <!--  #this div is html div that will render your partial-->
            
          <!--</div>-->
          <div class="dropdown">
            <button class="dropbtn">FILTER BY</button>
            <div class="dropdown-content">
              <a href="latest">Latest</a>
              <a href="popular">Popular</a>
              <a href="oldest">Oldest</a>
            </div>
          </div>
        </div>
      </div>
      <div class="container" id="photos">
        <div id="unsplash" >
        </div>
        <div id="more">
          <a class="more"><span>...</span></a>
          </div> 
      </div>
    <script src='http://juanvargas.net/Unsplash/js/jquery.min.js'></script>
    <script src='http://juanvargas.net/Unsplash/js/jquery.masonry.js'></script>
    <script src='http://juanvargas.net/Unsplash/js/imagesloaded.pkgd.js'></script>
    <script src="http://juanvargas.net/Unsplash/js/api.js"></script>
    <script>
      $('#unsplash').unsplash({
        client_id:'ac2440143679fe6cabdec3a7c05d19336e6985f38a5808992db62cac654e7a7b',
        limit:20,
        columns:2,
        width:1917
      });
    </script>
  </body>
</html>

app/views/home/photos.js.erb
$('#gallery').html("<%= escape_javascript(render :partial => 'photos') %>");

app/views/home/sponsor.html.erb
<style>
.container-fluid {
    width: 88%;
}

.main-panel{
width:100%;
margin-top: -1%;
}

.sidebar {
    display:none;
}

.card {
    box-shadow:none;
}

.title{
color:#364c56;
}

.category{
font-weight: 600;
font-size: 10px;
text-transform: uppercase;
}

.featurette {
margin-top: 10%;
}

.featurette-image{
width: 20%;
}

.featurette-heading{
margin-top: 10%;
}

.img-circle {
border-radius: 30%;
}
.category{
font-weight: 600;
font-size: 10px;
text-transform: uppercase;
}
</style>
<body>
<%= render 'home/sidebar' %>
<div class="wrapper">


    <div class="main-panel">

<!--header-->

<div class="content">
  <div class="container-fluid">
      <div class="row">
<!--card-->
<div class="col-md-12">
<h4 class="title">Sponsoring</h4>
<p class="category"> <%= link_to 'Back', home_about_path %> </p>
<div class="card">
<div class="header">

</div>
<!--<div class="content">-->
<p class="title" id="p-content">
    
Duis lobortis, nulla nec tempus scelerisque, quam odio iaculis nisi, in malesuada mauris nibh sed mauris. Sed in purus eleifend, blandit felis eget, eleifend neque. Vestibulum sit amet eleifend felis, ut venenatis diam. Aenean suscipit eros vitae placerat dapibus. Nullam feugiat tellus ligula, non pharetra diam efficitur nec. Etiam imperdiet arcu varius arcu suscipit, condimentum pulvinar risus vestibulum. Curabitur euismod tincidunt cursus. Ut id magna condimentum, congue turpis in, porta magna. Curabitur sit amet dui ut libero maximus dapibus sit amet in leo. Sed eu tempus libero. Pellentesque ac dignissim nibh. Nullam auctor enim in risus feugiat elementum. Cras non lorem scelerisque, eleifend sem et, cursus leo. Morbi imperdiet arcu ante, id dignissim turpis mattis et. Duis quis ante rutrum enim elementum gravida. Etiam tincidunt nisl ut purus faucibus, mattis dapibus erat tincidunt.
</p>
<!--<p></p>-->

<!--</div>-->

</div>
</div>
<!--end-->
   
       
</div>
</div>
</div>




</div>
</div>


</body>

</html>