config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :poems
  resources :galleries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :stories, :path => 'jobs'
  
  
  resources :people
  resources :pins, :path => 'history'
  devise_for :users
  root 'stories#index'
  devise_scope :user do get 'users/sign_out' => "devise/sessions#destroy"
  end
  
resources :startups, :path => 'directory'
  

  
  get 'home/photos'
  get 'home/index'
  get 'home/about', :path => 'about'
  get 'home/sponsor'
  

  resources :stories
  get "search", to: "search#search"

end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
    
    validates_formatting_of :event_image, using: :url
    validates_formatting_of :web_url, using: :url
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  skip_before_filter :correct_user, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @event = Event.all
    @event = Event.order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:summary, :event_image, :web_url, :name, :start_time, :end_time, :description, :location, :city, :organizer, :free)
    end
end

def correct_user
  @event = current_user.events.find_by(id: params[:id])
  redirect_to events_path, notice: "Not authorized to edit this event" if @event.nil?
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<style>
#main-container-footer {
  display: none;
}

#wrapper-copyright {
  display: none;
}
</style>
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Organizer_or_Organization %><br>
    <%= f.text_field :organizer, placeholder: 'Latino Community Fund', class: "form-control border-input" %>
  </div>

  <div class="form-group">
    <%= f.label :Event_Title %><br>
    <%= f.text_field :name, placeholder: 'Lets try to keep it short ', class: "form-control border-input" %>
  </div>
  
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, placeholder: 'Seattle', class: "form-control border-input" %>
  </div>
  
  <div class="form-group">
    <%= f.label :Venue %><br>
    <%= f.text_field :location, placeholder: 'Event Venue e.g Impact Hub', class: "form-control border-input" %>
  </div>
  
  <!--mints Gallery-->
    <div id="page-head-text-hide-on-mobile">
    <!--<hr style="border-top: 1px solid #00d49b;">-->
    <%= link_to home_photos_path, target: "_blank" do %><i style="font-size: 25px;" class="fa fa-camera" title="mints Gallery"></i><% end %>
    <span style="margin-left: 16%;"><strong>Click</strong> to explore images in the mints gallery.</span>
    <br>
    <br>
    <!--<hr style="border-top: 1px solid #00d49b;">-->
    <br>
    </div>
   <!--end-->
  
  <div class="form-group">
    <%= f.label :Event_image %><br>
    <%= f.text_field :event_image, placeholder: 'Image Url | Recommended  800 x 500', class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, placeholder: 'Share details about your event', class: "form-control border-input", :maxlength => 684, :size => 40 %>
  </div>
  <div class="form-group">
    <%= f.label :Short_description %><br>
    <%= f.text_area :description, placeholder: 'Provide a short description of the event | 187 Characters Max', :maxlength => 187, class: "form-control border-input" %>
  </div>
    <br>
    <br>
    <%= f.label :Is_the_event_free_?, required: true %><br>
    <%= f.check_box :free, {}, true %> <%= f.label :free, "Free" %><br> 
    <%= f.check_box :free, {}, false %> <%= f.label :no, "Ticket Required" %><br>
    <br>
    <br>
  
  <div class="form-group">
    <%= f.label :link %><br>
    <%= f.text_field :web_url, placeholder: 'External Link', class: "form-control border-input" %>
  </div>
  
  <div class="form-group">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time, class: "form-control border-input" %>
  </div>
  
 <!-- <div class="form-group">-->
	<!--<input class="datepicker form-control" type="text"/>-->
	<!--</div>-->
  
  <div class="form-group">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time, class: "form-control border-input" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
	 $('.datepicker').datepicker({
    	 weekStart:1,
    	 color: 'red'
	 });
</script>

app/views/events/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.1.erb
<html>
<head>
	  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<meta name="viewport" centent="width=device-width, initial-scale=1">
	
<style>
.wrapper {
}

.border{
	height: 6px;
	border:0;
	background-color: #fd7576;
	background-image: linear-gradient(to right, #fd7576, #fd7576 25%, #fec85d 25%, #fec85d 50%, #4db8de 50%, #4db8de 75%, #a378fc 75%, #a378fc 100%, #a378fc 100%);
	-webkit-background-size: 50% 100%;
  -moz-background-size: 50% 100%;
  background-size: 50% 100%; 
  
}

.clearfix:before, .clearfix:after {
	content:" ";
	display: table;

}
.clearfix:after{
	clear: both;
}
.wrapper{
	width:800px;
	max-width: 90%;
	margin: 0 auto;
	margin-top: 20%;
}
.main_header{
	margin: 5em 0 3em 0;
}

.current{
	color: #34324b;
	font-weight: 700;
	
}
#timeline{
  width: 100%;
  position: relative;
  list-style: none;
  padding: 0;

}
#timeline a {
text-decoration: none;

}
 #timeline:after {
    content: "";
    width: 1px;
    background: 1px #e6e7e9;
    height: 90%;
    position: absolute;
    top: 3em;
    left: 3em;
    z-index: 0; }
#timeline .listing{
  background-color: white;
  border: 1px solid #e6e7e9;
  border-radius: 0.3em;
  padding: 1em;
  margin-bottom: 1em;
  position: relative;
  z-index: 1;
  display: table;
  width: 100%;
  transition: all .3s ease-in-out;


}
.listing:hover{
  cursor: pointer;
  box-shadow: 0px 2px 40px 0 rgba(0,0,0,0.1);

}
#timeline .listing img,.info,.job_type{
  display: table-cell;
  vertical-align: middle;
  font-size: 0.9em;
  color: #74718f;

}


.info{
  line-height: 1.25;
  width: 640px;
  padding-left: 25px;
}
.job_title{
  font-weight: 700;
  font-size: 1.5em;
  color: #34324b;
}
.job_info{
  color: rgb(90, 90, 90);
  display: block;
  font-size: 15px;

}
.job_info span{
  margin: 0 .75em;
}
.job_type{
  text-transform: uppercase;
  font-weight: 700;
  font-size: 0.75em;
  position: relative;
  white-space: nowrap;
  padding-top: .6em;
  width: 100px;
}
.job_type:before{
  content: " ";
  background-color: #fd7576;
  width:10px;
  height: 10px;
  border-radius: 100%;
  position: absolute;
  left:-20px;
  top:27px;
}
.full_time{
  color: #00dda1;

}
.full_time:before{
background-color:#02d29a;
}
.part_time{
  color: #fec85d;

}
.part_time:before{
background-color:#fec85d;
}
.freelance{
  color: #4db8de;

}
.freelance:before{
background-color:#4db8de;
}
.contract{
  color: #a378fc;

}
.contract:before{
background-color:#a378fc;
}
.date{
  display: inline-block; 
  padding: 1em 0;
  width: 100px;
  background-color: white;
  border: 1px solid #e6e7e9;
  border-radius: 3em;
  font-weight: 700;
  font-size: .75em;
  text-align: center;
  z-index: 2;
  position: relative;
  margin : 1em 0 2em 0;
  color: #34324b;
}
.load_more{
  text-align: center;

}
.button{
  border : 2px solid #a378fc;
  outline: none;
  padding: 1em 3.5em;
  text-align: center;
  background: transparent;
  border-radius: 3em;
  color: #a378fc;
  transition:all .3s ease-in-out;
}

#main-container-footer{
}

#wrapper-copyright {
	display: none;
}

#wrapper-navbar {
    float: left;
    width: 100%;
    height: 60px;
    background-color: transparent;
    border-bottom: none;
    opacity: 1;
    z-index: 100;
    position: absolute;
    /* color: white !important; */
}

.top-rated {
	color: #fff !important;
}

.button:hover{
 background-color: #a378fc;
  color: white;

}
@media only screen and (max-width: 768px){
  .main_header{
  margin: 3em 0;
}
}

@media only screen and (min-device-width : 375px) and (max-device-width : 667px) { 
img {
	width: %;
	
	}
}

@media only screen and (min-device-width : 375px) and (max-device-width : 667px) { 
.jumbotron .content {
	top: 40% !important;
	
	}
}

@media only screen and (min-device-width : 375px) and (max-device-width : 667px) { 
.wrapper {
	margin-top: 70% !important;
	
	}
}

@media only screen and (min-device-width : 375px) and (max-device-width : 667px) { 
.jumbotron .content p.lead {
   letter-spacing: 4px;
	
	}
}

@media only screen and (min-device-width : 375px) and (max-device-width : 667px) { 
.part-info-image {
    margin-left: 40% !important;
    margin-top: -15% !important;

	
	}
}

.jumbotron {
	position: absolute;
	z-index: 1;
}

</style>
</head>	
<body>
	<div class="border"></div>
	<!--header image-->
    <div class="jumbotron text-center">
        <img src="https://images.unsplash.com/photo-1492305175278-3b3afaa2f31f?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1917&fit=max&s=1aabbccdf61bfdc460343977b9d9d58d">
   <!--     <div class="content">-->
   <!--         <div class="event-date"> </div>-->
   <!--         <h1 id="cursive-text">Events</h1>-->
   <!--         <p class="lead" style="font-family: Pacifico;">Here's to Keeping it Local. </p>-->
			<!--button was removed-->
   <!--     </div>-->
    </div>
<!--header end-->
	<div class="wrapper">
<div class="part-info-image" style="z-index: 100;
    position: absolute !important;margin-left: 20%;
    margin-top: -5%;
    color: #E91E63 !important;"><%= link_to new_event_path do %><i style="font-size: 30px; .part-info-image {
}" class="fa fa-plus-circle" title="Post an Event"></i><% end %></div>
		<ul id="timeline">
		  
	<% @event.each do |event| %>
      <a href="#">
        <li class="listing clearfix">
          <div class="image_wrapper">
            <%= link_to image_tag(event.event_image), event %>
          </div>
          <div class="info">
            <span class="job_title"><%= event.name %></span>
            <br>
            <br>
            <span class="job_info"><span> <%= event.location %></span>  <span>|</span>  <strong><%= event.city %></strong></span>
          </div>
          <span class="job_type full_time" style="color: "><%= event.start_time.strftime("%b %d") %></span>
        </li>
      </a>
	<% end %>
     
    </ul>
	<div class="load_more">
		<%= will_paginate @event %>
	</div>
</body>
</html>

app/views/events/index.html.erb
<body>
<%= render 'home/sidebar' %>
<div class="wrapper">


<div class="main-panel">
<!--header-->
<div class="content">
  <div class="container-fluid">
      <div class="row">
<!--permanent card-->
    <div class="col-lg-3 col-sm-6">
<div class="card">
    <div class="content">
        <div class="row">
          
            <div class="col-xs-5">
                <div class="icon-big icon-warning text-center">
                <%= image_tag('mints-logo.png') %>
                </div>
            </div>
            <div class="col-xs-7">
                <div class="numbers">
                    <p>Post your Event</p>
                    <br>
                    
                </div>
            </div>
        </div>
        <div class="footer">
            <hr />
            <div class="stats">
                <%= link_to new_event_path do %><i style="font-size: 30px; .part-info-image {
}" class="fa fa-plus-circle" title="Post an Event"></i><% end %>
            </div>
        </div>
    </div>
</div>
</div>
<!--end-->
        <% @event.each do |event| %>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                        
                          <div class="col-xs-5">
                              <div class="icon-big icon-warning text-center">
                                <%= image_tag(event.event_image, class: 'post-logo') %>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p><%= link_to truncate(event.name, length: 25), event %></p>
                                  <br>
                                  <%= event.start_time.strftime("%b %d") %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">

                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!--job listings-->
        <% end %>
      </div>
      <%= will_paginate @event %>
        </div>
    </div>




</div>
</div>

</body>

</html>
<!-- current_user.events.count -->

app/views/events/new.html.erb
<%= render 'home/sidebar' %>
<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><%= @event.name %></title>

    <!-- favicon -->
    <link href="favicon.png" rel=icon>

    <!-- web-fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag 'bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Style CSS -->
    <%= stylesheet_link_tag 'eventstyle', media: 'all', 'data-turbolinks-track' => true %>
    
    <!-- jquery -->
    <%= javascript_include_tag 'jquery-2.1.4.min.js', 'data-turbolinks-track' => true %>
    <!-- Bootstrap -->
    <%= javascript_include_tag 'bootstrap.min.js', 'data-turbolinks-track' => true %>
    
    <!-- Plugin JavaScript -->
    <%= javascript_include_tag 'jquery.easing.min.js', 'data-turbolinks-track' => true %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
.content {
    top: 40% !important;
}

.navbar {
    display: none;
}

#post-content {
    line-height: 37px;
    font-size: 20px;
    letter-spacing: 1px;
    font-family: 'Playfair Display', serif;
    margin-left: 0% !important;
    margin-top: -4%;
    font-weight: 600;
}
#wrapper-navbar {
    display: none;
}
#wrapper-header {
    display: none;
}

#main-container-footer{
    display:none;
}

.main-menu .navbar-right {
    display: none !important;
}

.container {
    position: initial;
}

.sticky-nav {
    background: transparent !important;
}

.navbar {
    position: initial;
}

</style>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar">
<div id="main-wrapper">
    <!-- Page Preloader -->
    <div id="preloader">
        <div id="status">
            <div class="status-mes"></div>
        </div>
    </div>

    <header class="header">
        <!-- Navigation -->
        <nav class="navbar main-menu" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand page-scroll" href="#page-top"><%= link_to image_tag("mints-logo.png"), root_path %></a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                        <li class="hidden"><a href="#page-top"></a></li>
                        <li><a class="page-scroll" href="#section-intro">About</a></li>
                        <li><a class="page-scroll" href="#section-speaker">Speaker</a></li>
                        <li><a class="page-scroll" href="#section-ajenda">Agenda</a></li>
                        <li><a class="page-scroll" href="#section-pricing">Buy Ticket</a></li>
                        <li><a class="page-scroll" href="#section-partner">Partners</a></li>
                        <li><a class="page-scroll" href="#section-venue">Venue</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- .nav -->

    </header>

    <div class="jumbotron text-center">
        <%= image_tag @event.event_image, class: "" %>
        <div class="content">
            <div class="event-date"><%= @event.start_time.strftime("%A, %b %d %Y @ %l:%M %p") %> | <%= @event.city %></div>
            <h1><%= @event.name %></h1>
            <p class="leads"><%= @event.description %></p>
            <button type="button" class="btn btn-default btn-lg"><%= link_to 'VISIT SITE', @event.web_url, target: "_blank", id: "" %></button>
        </div>
    </div>
    <br>
    <br>
    <!-- .Jumbotron-->
<% if current_user %>
<%= link_to edit_event_path @event do %><i style="font-size: 15px; margin-left: 50%; color: #009688;" class="fa fa-pencil"><% end %></i>
<% end %>

    <section id="section-intro" class="section-wrapper about-event">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <p class="lead" id="post-content">
                        <%= simple_format(@event.summary, id: "post-content") %>
                    </p>
                    <p class="lead"> </p>
                </div>
                <div class="col-md-4">
                    <address>
                        <strong>Where</strong><br>
                        <%= @event.location %>
                        <br>
                        <br>
                        <strong>When</strong><br>
                        <%= @event.start_time.strftime("%A, %b %d %Y @ %l:%M %p") %><br>
                        <em>Until</em><br>
                        <%= @event.end_time.strftime("%A, %b %d %Y @ %l:%M %p") %>
                        <br>
                    
                        <!--<strong>Free?</strong><br>-->
                        <!--<%= @event.free? %>-->
                        <!--<br>-->
                        <br>
                        <strong>Share</strong><br>
                        <abbr title="Phone">
<!--share on twitter-->
   <%= link_to "http://twitter.com/home?status=Check out this event  #{@event.name} #{event_url(@event)}", target: "_blank" do %><i style="font-size: 30px; color: #009688;" class="fa fa-twitter" title="Share on Twitter"></i><% end %></abbr> 
                    </address>
                </div>
            </div>
        </div>
    </section>
    <!-- .about-event -->

<!--Add new sections-->

<!--sponsors, schedule, speakers, etc-->

<!--new sections-->
    

            <!--<div class="row">-->
            <!--    <div class="col-md-12">-->
            <!--        <div class="section-title">-->
            <!--            <h2>STAY INFORMED</h2>-->
            <!--            <p>Don't miss the event!</p>-->
            <!--        </div>-->
            <!--        <form id="contactForm" class="subscribe-form form-inline" action="sendemail.php" method="POST">-->
            <!--            <div class="form-group">-->
            <!--                <label for="emailTwo" class="sr-only">Email</label>-->
            <!--                <input type="email" class="form-control input-lg" required="" id="emailTwo" name="email" placeholder="Enter your email address">-->
            <!--            </div>-->
            <!--            <button type="submit" class="btn btn-primary btn-lg">SUBSCRIBE</button>-->
            <!--        </form>-->
            <!--    </div>-->
            <!--</div>-->

        </div>
    </section>
    <!-- contact-section -->

    <!-- .footer -->

</div>
<!-- #main-wrapper -->
<script>
    $( document ).ready(function() {
    console.log( "ready!" );
});

</script>


<!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->


<!--<script src="js/one-page-nav.js"></script>-->
<%= javascript_include_tag 'scripts', 'data-turbolinks-track' => false %>
</body>
</html>